/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as FormRouteImport } from './routes/form'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodosIndexRouteImport } from './routes/todos/index'
import { Route as TodosTodoIdIndexRouteImport } from './routes/todos/$todoId/index'
import { Route as TodosTodoIdEditRouteImport } from './routes/todos/$todoId/edit'

const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosIndexRoute = TodosIndexRouteImport.update({
  id: '/todos/',
  path: '/todos/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosTodoIdIndexRoute = TodosTodoIdIndexRouteImport.update({
  id: '/todos/$todoId/',
  path: '/todos/$todoId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosTodoIdEditRoute = TodosTodoIdEditRouteImport.update({
  id: '/todos/$todoId/edit',
  path: '/todos/$todoId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/form': typeof FormRoute
  '/timetable': typeof TimetableRoute
  '/todos': typeof TodosIndexRoute
  '/todos/$todoId/edit': typeof TodosTodoIdEditRoute
  '/todos/$todoId': typeof TodosTodoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/form': typeof FormRoute
  '/timetable': typeof TimetableRoute
  '/todos': typeof TodosIndexRoute
  '/todos/$todoId/edit': typeof TodosTodoIdEditRoute
  '/todos/$todoId': typeof TodosTodoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/form': typeof FormRoute
  '/timetable': typeof TimetableRoute
  '/todos/': typeof TodosIndexRoute
  '/todos/$todoId/edit': typeof TodosTodoIdEditRoute
  '/todos/$todoId/': typeof TodosTodoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/form'
    | '/timetable'
    | '/todos'
    | '/todos/$todoId/edit'
    | '/todos/$todoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/form'
    | '/timetable'
    | '/todos'
    | '/todos/$todoId/edit'
    | '/todos/$todoId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/form'
    | '/timetable'
    | '/todos/'
    | '/todos/$todoId/edit'
    | '/todos/$todoId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FormRoute: typeof FormRoute
  TimetableRoute: typeof TimetableRoute
  TodosIndexRoute: typeof TodosIndexRoute
  TodosTodoIdEditRoute: typeof TodosTodoIdEditRoute
  TodosTodoIdIndexRoute: typeof TodosTodoIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/': {
      id: '/todos/'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/$todoId/': {
      id: '/todos/$todoId/'
      path: '/todos/$todoId'
      fullPath: '/todos/$todoId'
      preLoaderRoute: typeof TodosTodoIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/$todoId/edit': {
      id: '/todos/$todoId/edit'
      path: '/todos/$todoId/edit'
      fullPath: '/todos/$todoId/edit'
      preLoaderRoute: typeof TodosTodoIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FormRoute: FormRoute,
  TimetableRoute: TimetableRoute,
  TodosIndexRoute: TodosIndexRoute,
  TodosTodoIdEditRoute: TodosTodoIdEditRoute,
  TodosTodoIdIndexRoute: TodosTodoIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
