/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormsJobApplicationRouteImport } from './routes/forms/job-application'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsJobApplicationRoute = FormsJobApplicationRouteImport.update({
  id: '/forms/job-application',
  path: '/forms/job-application',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forms/job-application': typeof FormsJobApplicationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forms/job-application': typeof FormsJobApplicationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forms/job-application': typeof FormsJobApplicationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/forms/job-application'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/forms/job-application'
  id: '__root__' | '/' | '/forms/job-application'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormsJobApplicationRoute: typeof FormsJobApplicationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/job-application': {
      id: '/forms/job-application'
      path: '/forms/job-application'
      fullPath: '/forms/job-application'
      preLoaderRoute: typeof FormsJobApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormsJobApplicationRoute: FormsJobApplicationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
